name: deploy CD

on:
  push:
    branches:
      - main
jobs:
  Deploy-Preview:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 18
            
        - name: Package install
          run: yarn install

        - name: Build project
          run: yarn build

        - name: Deploy to Vercel
          uses: amondnet/vercel-action@v25
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }} # required
            vercel-org-id: ${{ secrets.ORG_ID}}  #required
            vercel-project-id: ${{ secrets.PROJECT_ID}} #required 
            github-token: ${{ secrets.GITHUB_TOKEN }} #optional 
            vercel-args: '--yes'  #say yes

