name: deploy CD
env:
  #THIS IS PROJECT INFORMATION WHICH COMES FROM .VERCEL/PROJECT.JSON FILE.
  # THIS KEY VALUE STORE IN GITHUB ACTION. 
  # GITHUB.COM > SETTINGS > SECRETS AND VARIABLES > ACTIONS > REPOSITORY SECRETS.
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-development:
    runs-on: ubuntu-latest
    steps:
      #Checkout and setup node
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.x

      #INSTALL DEPENDENCIES
      - name: Install dependencies
        run: yarn install  

      #Build
      - name: Build Project
        run: yarn build

      #DEPLOY
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          yarn global add vercel@latest
          vercel --prod --token=$VERCEL_TOKEN --confirm --local-config vercel.json
