name: Run Unit Tests and Lint Files CI
on: [push, pull_request]

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.x

      - name: Package install
        run: yarn install
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.x

      - name: Package install
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Coverage report
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: "./coverage/coverage-summary.json"
          json-final-path: "./coverage/coverage-final.json"
